#!/bin/bash
/usr/bin/clear
#
# erases recursive temporary files generated by latex, that causes latex to explode sometimes, eg 
# when you are forced to use stupid htwk tex templates, which are packed with tons of temporary files
# 
# usage: call script in the root directory of your document folder
#

# directory from which to begin recursively "." means from the directory where the script from is called
DIRECTORY="./"

## put all file extensions here, separated by backslash pipe, last extension has to be terminated by backslash only ! 
EXPRESSION=("-regex" ".*\.\(acn\|acr\|alg\|aux\|bak\|bbl\|blg\|glg\|glo\|gls\|gz\|idx\|ilg\|ind\|ist\|lof\|log\|lot\|nlo\|nls\|out\|\synctex\|synctex.gz(busy)\|tcp\|toc\|tps\)" )

#### no user config beyond this line ############################################################################################################################################################
find "$DIRECTORY" "${EXPRESSION[@]}" -exec echo {} \;   # list found files
echo;
echo;
echo;
echo "=======================================================================================";
echo -n "= Files found: ";
find "$DIRECTORY" "${EXPRESSION[@]}" -exec echo {} \; | wc -l   # count found files
echo "=";
echo "= press [ctrl]+[c] to abort or every other key to erase files"
echo "=======================================================================================";
#now wait for user input
read -n1 -s

find "$DIRECTORY" "${EXPRESSION[@]}" -exec rm {} \; # remove found files

